# TP1 TENSORFLOW

## Guide des fondamentaux de Tensorflow

1) Créez un vecteur, un scalaire, une matrice et un tenseur avec les valeurs de votre choix en utilisant tf.constant().

In [3]:
# Importer TensorFlow
import tensorflow as tf
print(tf.__version__) # trouve le numéro de version (devrait être 2.x+)


2.3.0


In [4]:
# Créer un scalaire (tenseur de rang 0)
scalaire = tf.constant(8)
scalaire

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [5]:
# Vérifier le nombre de dimensions d'un tenseur (ndim signifie nombre de dimensions)
scalaire.ndim

0

In [6]:
# Créer un vecteur (plus de 0 dimensions)
vecteur = tf.constant([12, 12])
vecteur
vecteur.ndim 

1

In [8]:
# Créer une matrice (plus d'une dimension)
matrice = tf.constant([[12, 8],
 [8, 12]])
matrice

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  8],
       [ 8, 12]])>

In [9]:
matrice.ndim 

2

In [10]:
tenseur = tf.constant([[[1, 2, 3],
 [4, 5, 6]],
 [[7, 8, 9],
 [10, 11, 12]],
 [[13, 14, 15],
 [16, 17, 18]]] , dtype=tf.float16)
tenseur

<tf.Tensor: shape=(3, 2, 3), dtype=float16, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.]]], dtype=float16)>

In [11]:
tenseur.ndim

3

#### Création de tenseurs avec tf.Variable()

In [12]:
# Créez le même tenseur avec tf.Variable() et tf.constant()
tenseur_changeable = tf.Variable([12, 8])
tenseur_unchangeable = tf.constant([12, 8])
tenseur_changeable, tenseur_unchangeable


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12,  8])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([12,  8])>)

In [13]:
tenseur_changeable [0].assign(8)
tenseur_changeable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 8])>

In [14]:
tenseur_unchangeable [0].assign(8)
tenseur_unchangeable

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

#### Créer des tenseurs aléatoires 

In [52]:
# Créer deux tenseurs aléatoires (et différents si vous voulez les même utiliser même seed)
random1 = tf.random.Generator.from_seed(50)
random1 = random1.normal(shape=(3, 2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.45331386,  1.1487608 ],
       [-1.2659091 , -0.47450137],
       [ 2.006022  ,  0.28288034]], dtype=float32)>

In [53]:
random2 = tf.random.Generator.from_seed(15)
random2 = random2.normal(shape=(3, 2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.33149973, -0.5445254 ],
       [ 1.5222508 ,  0.59303206],
       [-0.63509274,  0.3703566 ]], dtype=float32)>

In [54]:
# Vérifiez les tenseurs et voyez s'ils sont égaux
random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.45331386,  1.1487608 ],
        [-1.2659091 , -0.47450137],
        [ 2.006022  ,  0.28288034]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [59]:
# Vérifiez les tenseurs et voyez s'ils sont égaux
random2, random2, random1 == random1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [88]:
#Mélangez un tenseur (utile lorsque vous souhaitez mélanger vos données)
non_melanger = tf.constant([[12, 8],
 [5, 4],
 [6, 5]])
# Obtient des résultats différents à chaque fois
tf.random.shuffle(non_melanger)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  5],
       [ 5,  4],
       [12,  8]])>

In [94]:
# Mélangez dans le même ordre à chaque fois en utilisant le paramètre seed (ne sera pas réellement le même)
tf.random.shuffle(non_melanger, seed=50)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  5],
       [12,  8],
       [ 5,  4]])>

In [41]:
# Mélanger dans le même ordre à chaque fois
# Définir le seed aléatoire globale, et si vous commentez ceci, vous obtiendrez des résultats différents
tf.random.set_seed(50)

In [44]:
# Définir l’opération du seed aléatoire 
tf.random.shuffle(non_melanger, seed=50)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  4],
       [12,  8],
       [ 6,  5]])>

#### Autres façons de fabriquer des tenseurs

In [46]:
# Faire un tenseur de tous les uns
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [47]:
# Faire un tenseur de tous les zéros
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

2) Trouvez la forme, le rang et la taille des tenseurs que vous avez créés en 1.

In [48]:
# Créer un tenseur de rang 4 (4 dimensions)
tenseur_rang_4 = tf.zeros([6, 7, 8, 9])
tenseur_rang_4

<tf.Tensor: shape=(6, 7, 8, 9), dtype=float32, numpy=
array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0.,

In [49]:
tenseur_rang_4.shape, tenseur_rang_4.ndim, tf.size(tenseur_rang_4)
# Obtenir divers attributs de tenseur
print("Type de données de chaque élément :", tenseur_rang_4.dtype)
print("Nombre de dimensions (rang) :", tenseur_rang_4.ndim)
print("Forme du tenseur :", tenseur_rang_4.shape)
print("Éléments le long de l'axe 0 du tenseur :", tenseur_rang_4.shape[0])
print("Éléments le long du dernier axe du tenseur :", 
tenseur_rang_4.shape[-1])
print("Nombre total d'éléments (6*7*8*9):",tf.size(tenseur_rang_4).numpy()) 
# . numpy() convertit en tableau NumPy

Type de données de chaque élément : <dtype: 'float32'>
Nombre de dimensions (rang) : 4
Forme du tenseur : (6, 7, 8, 9)
Éléments le long de l'axe 0 du tenseur : 6
Éléments le long du dernier axe du tenseur : 9
Nombre total d'éléments (6*7*8*9): 3024


In [50]:
tenseur2_rang_4 = tf.zeros([3, 2, 4, 5])
tenseur2_rang_4

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

#### 3) Multipliez deux tenseurs en utilisant la multiplication matricielle.

Manipuler des tenseurs (opérations tensorielles)

In [62]:
# Vous pouvez ajouter des valeurs à un tenseur en utilisant l'opérateur d'addition
Otenseur = tf.constant([[12, 8], [6, 8]])
Otenseur

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  8],
       [ 6,  8]])>

In [63]:
Otenseur + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 18],
       [16, 18]])>

In [64]:
# Multiplication (connue sous le nom de multiplication élément par élément)
Otenseur * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120,  80],
       [ 60,  80]])>

In [65]:
# Soustraction
Otenseur - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2, -2],
       [-4, -2]])>

In [66]:
# Utilisez la fonction tensorflow équivalente à l'opérateur '*' (multiplier)
tf.multiply(Otenseur, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120,  80],
       [ 60,  80]])>

In [67]:
# Multiplication matricielle dans TensorFlow
print(Otenseur)
tf.matmul(Otenseur, Otenseur)

tf.Tensor(
[[12  8]
 [ 6  8]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[192, 160],
       [120, 112]])>

In [78]:
# Créer (3, 2) tenseur
X = tf.constant([[2, 1],
 [5, 4],
 [3, 6]])
# Créer un autre (3, 2) tenseur
Y = tf.constant([[8, 8],
 [4, 9],
 [10, 11]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 1],
        [5, 4],
        [3, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 8,  8],
        [ 4,  9],
        [10, 11]])>)

In [79]:
# Exemple de reshape (3, 2) -> (2, 3)
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 8,  8,  4],
       [ 9, 10, 11]])>

In [80]:
# Essayez la multiplication matricielle avec Y remodelé
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[25, 26, 19],
       [76, 80, 64],
       [78, 84, 78]])>

In [81]:
# Essayez la multiplication matricielle
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 66,  94],
       [ 84, 110]])>

In [82]:
# Vous pouvez obtenir le même résultat avec des paramètres
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 66,  94],
       [ 84, 110]])>

#### 4) Multipliez deux tenseurs en utilisant le produit scalaire.

Le produit scalaire

In [83]:
# Effectuer le produit scalaire sur X et Y (nécessite la transposition de X)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 66,  94],
       [ 84, 110]])>

Trouver le min, max, moyenne, somme (agrégation)

In [85]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 1],
        [5, 4],
        [3, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 8,  8],
        [ 4,  9],
        [10, 11]])>)

In [97]:
tf.reduce_min(X)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [98]:
tf.reduce_mean(X)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [99]:
X = tf.constant(5)
Y = tf.constant(12)
X,Y

(<tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>)

In [100]:
Z = tf.multiply(X,Y)
print(Z)

tf.Tensor(60, shape=(), dtype=int32)


In [103]:
with tf.compat.v1.Session() as session:
    X = tf.constant(5)
    Y = tf.constant(12)
    Z = tf.multiply(X,Y)
    print(session.run(Z))

60


In [105]:
with tf.compat.v1.Session() as session:
    A = tf.compat.v1.placeholder(tf.int64, name = 'A')
    print(session.run(2 * A, feed_dict = {A: 3}))
    session.close()

6


# Partie 2 : Application du Tensorflow dans le Deep Learning

#### 1 – Importation des bibliothèques nécessaire 

In [1]:
import math
import numpy as np
import h5py
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.python.framework import ops
from tf_utils import load_dataset, random_mini_batches, convert_to_one_hot, predict

%matplotlib inline
np.random.seed(1)

In [2]:
tf.compat.v1.disable_eager_execution() 
tf.compat.v1.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
def sigmoid(z):
    x=tf.compat.v1.placeholder(tf.float32, name = "x")
    sigmoid=tf.sigmoid(x)
    
    with tf.compat.v1.Session() as session: 
        # Exécutez l'initialisation des variables (si nécessaire), exécutez les opérations
        g = session.run(sigmoid, feed_dict = {x: z})
        # Cela s'occupe de fermer la session pour vous
    return g

In [4]:
print ("sigmoid(2) = " + str(sigmoid(2)))
print ("sigmoid(14) = " + str(sigmoid(14)))

sigmoid(2) = 0.8807971
sigmoid(14) = 0.99999917


Calcul du coût

In [5]:
def cost(logits, labels):
    """
    Calcule le coût en utilisant l'entropie croisée sigmoïde

    Arguments:
    logits -- vecteur contenant z, sortie de la dernière unité linéaire 
    (avant l'activation finale du sigmoïde)
    labels -- vecteur de label y 


    Returns:
    J -- exécute la session du coût (formula (2))
    """
 
 ### Insérer le code ICI ###
     # Créez les espaces réservés pour (z) et (y) (environ 2 lignes)
    z = tf.compat.v1.placeholder(tf.float32, name='z')
    y = tf.compat.v1.placeholder(tf.float32, name='y')
    
     # Utilisez la fonction de perte (env. 1 ligne)
    J = tf.nn.sigmoid_cross_entropy_with_logits(logits = z, labels = y)

     # Créer une session (env. 1 ligne). Voir la méthode 1 ci-dessus.
    sess = tf.compat.v1.Session()
     # Exécutez la session (environ 1 ligne).
    J = sess.run(J, feed_dict={z: logits, y: labels})
    
     # Fermez la session (env. 1 ligne). Voir la méthode 1 ci-dessus.
    sess.close()
    
    return J

In [6]:
z = sigmoid(np.array([0.2,0.4,0.7,0.9]))
J = cost(z, np.array([0,0,1,1]))
print ("J = " + str(J))

J = [1.0053873  1.0366408  0.41385433 0.39956617]


Utilisation des encodages One Hot

In [7]:
def matrice_one_hot(labels, A):
    """
    Crée une matrice où la i-ème ligne correspond au i-ème numéro de 
    classe et la j-ème colonne correspond au j-ème exemple 
    d'apprentissage. Donc, si l'exemple j avait un label i. Alors entrée 
    (i,j) sera 1. 

    Arguments:
    labels – un vecteur contient les labels
    A – numéro de classes

    Returns: 
    hot – matrice ‘one hot’
    """
 
    ### Insérer le code ICI ###

    # Créez un tf.constant égal à A (profondeur), nommez-le 'A'. (environ 1 ligne) 
    A = tf.constant(A, name='A')
    # Utilisez tf.one_hot, soyez prudent avec l'axe (environ 1 ligne)
    one_hot_matrice = tf.one_hot(labels, A, axis=0)
    # Créer la session (env. 1 ligne)
    sess = tf.compat.v1.Session()
    # Lancer la session (env. 1 ligne)
    hot = sess.run(one_hot_matrice)
    # Fermez la session (env. 1 ligne). Voir la méthode 1 ci-dessus.
    sess.close()
    
    return hot


In [8]:
labels = np.array([1,2,3,0,2,1])
one_hot = matrice_one_hot(labels, A = 4)
print ("one_hot = " + str(one_hot))

one_hot = [[0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]]
